### ISSUE TITLE
Keep showing for a while

### ISSUE THREAD

**Issue by noplanman** [EFForg/ngw-banner#14]
IMHO it would make sense to not just close the popup when clicking anywhere or waiting a while.
The whole point is to "block" access temporarily, to make the user really feel it for a moment.

I feel that being able to click it away instantly is too easy, especially as this is something for just a day (hopefully!).

So alternatively I'd suggest to either only allow clicking it away after 5 seconds or something, or only by explicitly clicking the buttons. Having it close itself after 5 seconds, as it is now, seems quite pointless to me, especially for people who tend to open pages in tabs and wait for them to fully load.

I really don't feel it's too obtrusive, and since it only happens once per page (as a cookie is stored to remember) it's no big deal to wait those few seconds, giving a user some time to think what it's like when Net Neutrality really goes down.

**Comment by lenazun** [comment]
Hello! Thank you for the feedback.
There's a variable in the code where you can change the time for frame switching, here
https://github.com/EFForg/dayofaction-banner/blob/gh-pages/banner_content/netneutrality17/js/main.js#L26

I hope that resolves your issue! Let us know.

**Comment by noplanman** [comment]
Kind of, what I mean is this actually:
https://github.com/EFForg/dayofaction-banner/blob/gh-pages/banner_content/netneutrality17/js/main.js#L19

It can just be clicked away too easily in my opinion. Of course it's bad practice to have a modal window that hijacks the whole screen, but I just feel that the cause of this popup is way more important than that.

Just my 2c 😇
