### ISSUE TITLE
Make fully accessible

### ISSUE THREAD

**Issue by noplanman** [EFForg/ngw-banner#15]
I'm not sure if this is already the case, as I don't have a screen reader to test this as a blind or partially sighted person, but it would obviously make sense to make the banner legible for all 🎉

**Comment by lenazun** [comment]
Hello! 
In terms of accessibility, we checked it with WAVE and had a sight-impaired friend take a look at it. Not completely thorough testing, to be sure :) Do you have any specific suggestions on aspects to improve?

**Comment by noplanman** [comment]
Off the top of my head, a screen reader only text that explains the popup would be good I think.
So that people who can't see / get the effect of the "Blocked" message at least know what it's supposed to be.
Otherwise it just reads out like something to buy.

I'll ask a blind friend of mine to have a look (😄) at it and give me her view (😂).

Then I'll post back with some more helpful input!

**Comment by noplanman** [comment]
Got some feedback and my blind friends say it's fully accessible 👍
